#!/bin/bash

CURRENT_PROFILE=$(pacmd list-cards | grep "active profile" | cut -d ' ' -f 3-)

if [ "$CURRENT_PROFILE" = "<output:hdmi-stereo>" ]; then
        pacmd set-card-profile 0 "output:analog-stereo+input:analog-stereo"
	notify-send "Laptop Audio"
else 
        pacmd set-card-profile 0 "output:hdmi-stereo"
	notify-send "HDMI Audio"
fi
