#!/bin/sh

# dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop

i3lock --nofork --blur=10 \
    --insidecolor=373445cc --ringcolor=ffffffcc --line-uses-inside \
    --keyhlcolor=61AFEFcc --bshlcolor=C678DDcc --separatorcolor=00000000 \
    --insidevercolor=71eeb8cc --insidewrongcolor=E06C75cc \
    --ringvercolor=ffffffcc --ringwrongcolor=ffffffcc \
    --radius=100 --veriftext="" --wrongtext="" --noinputtext="" \
    --ring-width=13 --timecolor=FDFDFDFF --datecolor=FDFDFDFF

