#!/bin/sh

LINE=$(ps -ef | fzf)
PROCESS=$(echo $LINE | awk '{ print " "$8" "$9" "$10 }')
UPTIME=$(echo $LINE | awk '{ print $7 }')
USER=$(echo $LINE | awk '{ print $1 }')
PID=$(echo $LINE | awk '{ print $2 }')
PROMPT=$(printf "No\\nYes" | fzf --prompt="Kill Process? " --header="Process: $PROCESS Uptime: $UPTIME User: $USER")

if [ "$PROMPT" == "Yes" ]
then
        kill $PID
        echo "$PROCESS with PID: $PID was killed"
else
        echo "merk aborted"
fi
