#!/bin/sh
#icon=$HOME/pictures/lock.png
tmpbg=/tmp/screen.png
scrot /tmp/screen.png
convert $tmpbg -scale 10% -scale 1000% $tmpbg
#magick $tmpbg -channel RGBA -blur 0x6 $tmpbg
convert $tmpbg $icon -gravity center -composite -matte $tmpbg
convert $tmpbg -gravity center -composite -matte $tmpbg
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Stop
i3lock --nofork -i $tmpbg \
    --insidecolor=373445cc --ringcolor=ffffffcc --line-uses-inside \
    --keyhlcolor=61AFEFcc --bshlcolor=C678DDcc --separatorcolor=00000000 \
    --insidevercolor=71eeb8cc --insidewrongcolor=E06C75cc \
    --ringvercolor=ffffffcc --ringwrongcolor=ffffffcc \
    --radius=80 --veriftext="" --wrongtext="" --noinputtext="" \
    --ring-width=10
