#!/bin/sh

if [ -d ~/usb ]; then
        if [[ -z $(findmnt /dev/sda1) ]]; then
                sudo -k mount /dev/sda1 ~/usb && echo 'USB Drive Mounted' ||\
                        (echo 'USB Mount Failed' && rmdir ~/usb)
        else
                sudo -k umount ~/usb && echo USB Drive Unmounted &&\
                rmdir ~/usb || echo 'USB Unmount Failed'
        fi
else
        mkdir ~/usb
        sudo -k mount /dev/sda1 ~/usb && echo USB Drive Mounted ||\
                (echo 'USB Mount Failed' && rmdir ~/usb)
fi
