#!/bin/sh

if [ -d ~/windows ]; then
        if [[ -z $(findmnt /dev/nvme0n1p3) ]]; then
                sudo -k mount /dev/nvme0n1p3 ~/windows &&\
                        echo 'Windows Drive Mounted' ||\
                        (echo 'Windows Mount Failed' && rmdir ~/windows)
        else
                sudo -k umount ~/windows && echo Windows Drive Unmounted &&\
                rmdir ~/windows || echo 'Windows Unmount Failed'
        fi
else
        mkdir ~/windows
        sudo -k mount /dev/nvme0n1p3 ~/windows && echo Windows Drive Mounted ||\
                (echo 'Windows Mount Failed' && rmdir ~/windows)
fi
